var w=v();self.asyncProxyScriptBlob=new w;
function v(){function b(){this.b=["'use strict';"];this.n=this.f=null;this.e(v,"BlobScriptGenerator");this.i("var asyncProxyScriptBlob = new BlobScriptGenerator();")}b.prototype.e=function(b,e){if(this.f)throw Error("Cannot add member to AsyncProxyScriptBlob after blob was used");e&&(this.b.push("var "),this.b.push(e),this.b.push(" = "));this.b.push("(");this.b.push(b.toString());this.b.push(")();")};b.prototype.i=function(b){if(this.f)throw Error("Cannot add statement to AsyncProxyScriptBlob after blob was used");this.b.push(b)};
b.prototype.getBlob=function(){this.f||(this.f=new Blob(this.b,{type:"application/javascript"}));return this.f};b.prototype.O=function(){this.n||(this.n=URL.createObjectURL(this.getBlob()));return this.n};return b};function x(){function b(b){if(null===e)throw"AsyncProxy internal error: SubWorkerEmulationForChrome not initialized";this.l=++d;e[this.l]=this;self.postMessage({type:"subWorkerCtor",d:this.l,V:b})}var d=0,e=null;b.Q=function(b){e=b};b.prototype.postMessage=function(b,d){self.postMessage({type:"subWorkerPostMessage",d:this.l,data:b},d)};b.prototype.terminate=function(b,d){self.postMessage({type:"subWorkerTerminate",d:this.l},d)};self.asyncProxyScriptBlob.e(x,"SubWorkerEmulationForChrome");return b}
var y=x();function z(){function b(a,g,c,u){var l=this;u=u||{};var f=d.toString(),f=f.replace("SCRIPT_PLACEHOLDER",m.O()),f=URL.createObjectURL(new Blob(["(",f,")()"],{type:"application/javascript"}));l.j=[];l.g=[];l.r=[];l.s=[];l.m=new Worker(f);l.m.onmessage=function(a){e(l,a)};l.t=null;l.k=0;l.w=u.functionsBufferSize||5;l.p=[];l.m.postMessage({u:"ctor",W:a,N:g,c:c,a:++r,D:!1,T:b.C()})}function d(){importScripts("SCRIPT_PLACEHOLDER");AsyncProxy.AsyncProxySlave.I()}function e(a,g){var c=g.data.a;switch(g.data.type){case "functionCalled":--a.k;
n(a);break;case "promiseResult":var b=a.g[c];delete a.g[c];b.resolve(g.data.result);break;case "promiseFailure":b=a.g[c];delete a.g[c];b.reject(g.data.reason);break;case "userData":null!==a.t&&a.t(g.data.ba);break;case "callback":c=a.j[g.data.a];if(void 0===c)throw"Unexpected message from SlaveWorker of callback ID: "+g.data.a+". Maybe should indicate isMultipleTimesCallback = true on creation?";c.v||a.B(a.j[g.data.a]);null!==c.A&&c.A.apply(null,g.data.c);break;case "subWorkerCtor":var c=new Worker(g.data.V),
d=g.data.d;a.r[d]=c;a.s.push(c);c.onmessage=function(c){f(a,c.ports,!1,{u:"subWorkerOnMessage",d:d,data:c.data})};break;case "subWorkerPostMessage":c=a.r[g.data.d];c.postMessage(g.data.data);break;case "subWorkerTerminate":c=a.r[g.data.d];c.terminate();break;default:throw"Unknown message from AsyncProxySlave of type: "+g.data.type;}}function f(a,g,c,b){a.k>=a.w?a.p.push({aa:g,R:c,message:b}):k(a,g,c,b)}function k(a,b,c,d){c&&++a.k;a.m.postMessage(d,b)}function n(a){for(;a.k<a.w&&0<a.p.length;){var b=
a.p.shift();k(a,b.aa,b.R,b.message)}}var m=self.asyncProxyScriptBlob,r=0,t=!1,p=function(){var a=location.href,b=a.lastIndexOf("/");0<=b&&(a=a.substring(0,b));return a}();b.prototype.$=function(a){this.t=a};b.prototype.terminate=function(){this.m.terminate();for(var a=0;a<this.s.length;++a)this.s[a].terminate()};b.prototype.L=function(a,b,c){c=c||{};var d=!!c.isReturnPromise,e=c.transferables,m=c.pathsToTransferablesInPromiseResult,h=++r,q=null,p=this;d&&(q=new Promise(function(a,b){p.g[h]={resolve:a,
reject:b}}));(c.isSendImmediately?k:f)(this,e,!0,{u:a,c:b||[],a:h,D:d,U:m});if(d)return q};b.prototype.ca=function(a,b,c){c=c||{};var d=++r;b={S:!0,v:!!c.isMultipleTimeCallback,a:d,M:b,F:c.pathsToTransferables};this.j[d]={v:!!c.isMultipleTimeCallback,a:d,A:a,F:c.pathsToTransferables};return b};b.prototype.B=function(a){delete this.j[a.a]};b.C=function(){t=!0;return p};b.J=function(a){if(p!==a&&t)throw"Previous values returned from getMasterEntryUrl is wrong. Avoid calling it within the slave c`tor";
p=a};m.e(z,"AsyncProxyMaster");return b}var A=z();function B(){function b(){var a=self[t],b=[null].concat(f(arguments));return new (Function.prototype.bind.apply(a,b))}function d(a,b){if(void 0!==a){for(var c=Array(a.length),d=0;d<a.length;++d){for(var e=a[d],f=b,h=0;h<e.length;++h)f=f[e[h]];c[d]=f}return c}}function e(a){var d=a.data.u,c=a.data.c,e=a.data.a,f=a.data.D,p=a.data.U;switch(d){case "ctor":self.AsyncProxy.AsyncProxyMaster.J(a.data.T);e=a.data.W;t=a.data.N;for(var h=0;h<e.length;++h)importScripts(e[h]);m=b.apply(null,c);return;case "subWorkerOnMessage":r[a.data.d].onmessage({data:a.data.data});
return}c=Array(a.data.c.length);for(h=0;h<a.data.c.length;++h){var q=a.data.c[h];void 0!==q&&null!==q&&q.S&&(q=k.G(q));c[h]=q}for(var h=m,n;h&&!(n=m[d]);)h=h.__proto__;if(!n)throw"AsyncProxy error: could not find function "+n;c=n.apply(m,c);f&&k.H(e,c,p);self.postMessage({type:"functionCalled",a:a.data.a,result:null})}function f(a){for(var b=Array(a.length),c=0;c<a.length;++c)b[c]=a[c];return b}var k={},n=null,m,r={},t;k.I=function(){self.onmessage=e};k.Z=function(a){b=a};k.Y=function(a){n=a};k.X=
function(a){self.postMessage({type:"userData",ba:a})};k.H=function(a,b,c){b.then(function(b){var e=d(c,b);self.postMessage({type:"promiseResult",a:a,result:b},e)})["catch"](function(b){self.postMessage({type:"promiseFailure",a:a,reason:b})})};k.G=function(a){var b=!1;return function(){if(b)throw"Callback is called twice but isMultipleTimeCallback = false";var c=f(arguments);null!==n&&n.call(m,"callback",a.M,c);var e=d(a.F,c);self.postMessage({type:"callback",a:a.a,c:c},e);a.v||(b=!0)}};k.o=function(){return C.o(Error())};
if(void 0===self.Worker){var p=self.SubWorkerEmulationForChrome;p.Q(r);self.Worker=p}self.asyncProxyScriptBlob.e(B,"AsyncProxySlave");return k}var D=B();function E(){function b(){this.q={};this.h=null}b.prototype.K=function(d){d=b.o(d);this.q[d]||(this.q[d]=!0,this.h=null)};b.prototype.P=function(){if(null===this.h){this.h=[];for(var b in this.q)this.h.push(b)}return this.h};b.o=function(b){var e=b.stack.trim(),f=/at (|[^ ]+ \()([^ ]+):\d+:\d+/.exec(e);if(f&&""!==f[2])return f[2];if((f=(new RegExp(/.+\/(.*?):\d+(:\d+)*$/)).exec(e))&&""!==f[1])return f[1];if(void 0!=b.fileName)return b.fileName;throw"ImageDecoderFramework.js: Could not get current script URL";
};self.asyncProxyScriptBlob.e(E,"ScriptsToImportPool");return b}var C=E();function F(){asyncProxyScriptBlob.e(F,"ExportAsyncProxySymbols");asyncProxyScriptBlob.i("ExportAsyncProxySymbols(SubWorkerEmulationForChrome, AsyncProxySlave, AsyncProxyMaster, ScriptsToImportPool);");asyncProxyScriptBlob.i("self['AsyncProxy']['AsyncProxySlave'] = AsyncProxySlave;");asyncProxyScriptBlob.i("self['AsyncProxy']['AsyncProxyMaster'] = AsyncProxyMaster;");asyncProxyScriptBlob.i("self['AsyncProxy']['ScriptsToImportPool'] = ScriptsToImportPool;");return function(b,d,e,f){self.AsyncProxy=
{};b.prototype.postMessage=b.prototype.postMessage;b.prototype.terminate=b.prototype.terminate;d.setSlaveSideCreator=d.Z;d.setBeforeOperationListener=d.Y;d.sendUserDataToMaster=d.X;d.wrapPromiseFromSlaveSide=d.H;d.wrapCallbackFromSlaveSide=d.G;e.prototype.setUserDataHandler=e.prototype.$;e.prototype.terminate=e.prototype.terminate;e.prototype.callFunction=e.prototype.L;e.prototype.wrapCallback=e.prototype.ca;e.prototype.freeCallback=e.prototype.B;e.getEntryUrl=e.C;f.prototype.addScriptFromErrorWithStackTrace=
f.prototype.K;f.prototype.getScriptsForWorkerImport=f.prototype.P}}F()(y,D,A,C);self.AsyncProxy.AsyncProxySlave=D;self.AsyncProxy.AsyncProxyMaster=A;self.AsyncProxy.ScriptsToImportPool=C;
