var m=function(){function e(a,b,f,c){var g=this;c=c||{};var k=p.toString(),n=l(),k=k.replace("SCRIPT_PLACEHOLDER",n),k=URL.createObjectURL(new Blob(["(",k,")()"],{type:"application/javascript"}));this.e=[];this.d=[];this.j=[];this.k=[];this.h=new Worker(k);this.h.onmessage=function(a){d(g,a)};this.l=null;this.f=0;this.o=c.functionsBufferSize||5;this.i=[];this.h.postMessage({m:"ctor",L:a,D:b,b:f,a:++r,s:!1,I:e.r()})}function p(){importScripts("SCRIPT_PLACEHOLDER");h.w()}function l(){var a=Error(),
b=(new RegExp(/.+\/(.*?):\d+(:\d+)*$/)).exec(a.stack.trim());if(b&&""!==b[1]||(b=(new RegExp(arguments.callee.name+" \\((.+?):\\d+:\\d+\\)")).exec(a.stack.trim()))&&""!==b[1])return b[1];if(void 0!=a.fileName)return a.fileName;throw"AsyncProxy.js: Could not get current script URL";}function d(a,b){var f=b.data.a;switch(b.data.type){case "functionCalled":--a.f;v(a);break;case "promiseResult":var c=a.d[f];delete a.d[f];c.resolve(b.data.result);break;case "promiseFailure":c=a.d[f];delete a.d[f];c.reject(b.data.reason);
break;case "userData":null!==a.l&&a.l(b.data.R);break;case "callback":f=a.e[b.data.a];if(void 0===f)throw"Unexpected message from SlaveWorker of callback ID: "+b.data.a+". Maybe should indicate isMultipleTimesCallback = true on creation?";f.n||a.q(a.e[b.data.a]);null!==f.p&&f.p.apply(null,b.data.b);break;case "subWorkerCtor":var f=new Worker(b.data.K),g=b.data.c;a.j[g]=f;a.k.push(f);f.onmessage=function(b){t(a,b.ports,!1,{m:"subWorkerOnMessage",c:g,data:b.data})};break;case "subWorkerPostMessage":f=
a.j[b.data.c];f.postMessage(b.data.data);break;case "subWorkerTerminate":f=a.j[b.data.c];f.terminate();break;default:throw"Unknown message from AsyncProxySlave of type: "+b.data.type;}}function t(a,b,c,d){a.f>=a.o?a.i.push({Q:b,G:c,message:d}):q(a,b,c,d)}function q(a,b,c,d){c&&++a.f;a.h.postMessage(d,b)}function v(a){for(;a.f<a.o&&0<a.i.length;){var b=a.i.shift();q(a,b.Q,b.G,b.message)}}var r=0,c=!1,n=function(){var a=location.href,b=a.lastIndexOf("/");0<=b&&(a=a.substring(0,b));return a}();e.prototype.P=
function(a){this.l=a};e.prototype.terminate=function(){this.h.terminate();for(var a=0;a<this.k.length;++a)this.k[a].terminate()};e.prototype.B=function(a,b,c){c=c||{};var d=!!c.isReturnPromise,g=c.transferables,e=c.pathsToTransferablesInPromiseResult,n=++r,l=null,p=this;d&&(l=new Promise(function(a,b){p.d[n]={resolve:a,reject:b}}));(c.isSendImmediately?q:t)(this,g,!0,{m:a,b:b||[],a:n,s:d,J:e});if(d)return l};e.prototype.S=function(a,b,c){c=c||{};var d=++r;b={H:!0,n:!!c.isMultipleTimeCallback,a:d,
C:b,t:c.pathsToTransferables};this.e[d]={n:!!c.isMultipleTimeCallback,a:d,p:a,t:c.pathsToTransferables};return b};e.prototype.q=function(a){delete this.e[a.a]};e.r=function(){c=!0;return n};e.A=function(a){if(n!==a&&c)throw"Previous values returned from getMasterEntryUrl is wrong. Avoid calling it within the slave c`tor";n=a};return e}();var u=function(){function e(d){if(null===l)throw"AsyncProxy internal error: SubWorkerEmulationForChrome not initialized";this.g=++p;l[this.g]=this;self.postMessage({type:"subWorkerCtor",c:this.g,K:d})}var p=0,l=null;e.F=function(d){l=d};e.prototype.postMessage=function(d,e){self.postMessage({type:"subWorkerPostMessage",c:this.g,data:d},e)};e.prototype.terminate=function(d,e){self.postMessage({type:"subWorkerTerminate",c:this.g},e)};return e}(),h=function(){function e(c){return new (Function.prototype.bind.apply(self[r],
[null].concat(c)))}function p(c,d){if(void 0!==c){for(var a=Array(c.length),b=0;b<c.length;++b){for(var f=c[b],e=d,g=0;g<f.length;++g)e=e[f[g]];a[b]=e}return a}}function l(c){var n=c.data.m,a=c.data.b,b=c.data.a,f=c.data.s,l=c.data.J;switch(n){case "ctor":m.A(c.data.I);b=c.data.L;r=c.data.D;for(var g=0;g<b.length;++g)importScripts(b[g]);q=e(a);return;case "subWorkerOnMessage":v[c.data.c].onmessage({data:c.data.data});return}a=Array(c.data.b.length);for(g=0;g<c.data.b.length;++g){var k=c.data.b[g];
void 0!==k&&null!==k&&k.H&&(k=d.u(k));a[g]=k}a=q.__proto__[n].apply(q,a);f&&d.v(b,a,l);self.postMessage({type:"functionCalled",a:c.data.a,result:null})}var d={},t=null,q,v={},r;d.w=function(){self.onmessage=l};d.O=function(c){e=c};d.N=function(c){t=c};d.M=function(c){self.postMessage({type:"userData",R:c})};d.v=function(c,d,a){d.then(function(b){var d=p(a,b);self.postMessage({type:"promiseResult",a:c,result:b},d)})["catch"](function(a){self.postMessage({type:"promiseFailure",a:c,reason:a})})};d.u=
function(c){var d=!1;return function(){if(d)throw"Callback is called twice but isMultipleTimeCallback = false";for(var a=Array(arguments.length),b=0;b<arguments.length;++b)a[b]=arguments[b];null!==t&&t("callback",c.C,a);b=p(c.t,a);self.postMessage({type:"callback",a:c.a,b:a},b);c.n||(d=!0)}};void 0===self.Worker&&(u.F(v),self.Worker=u);return d}();self.AsyncProxy={};self.AsyncProxy.AsyncProxySlave=h;self.AsyncProxy.AsyncProxyMaster=m;u.prototype.postMessage=u.prototype.postMessage;u.prototype.terminate=u.prototype.terminate;h.setSlaveSideCreator=h.O;h.setBeforeOperationListener=h.N;h.sendUserDataToMaster=h.M;h.wrapPromiseFromSlaveSide=h.v;h.wrapCallbackFromSlaveSide=h.u;m.prototype.setUserDataHandler=m.prototype.P;m.prototype.terminate=m.prototype.terminate;m.prototype.callFunction=m.prototype.B;m.prototype.wrapCallback=m.prototype.S;
m.prototype.freeCallback=m.prototype.q;m.getEntryUrl=m.r;
