var m=function(){function d(a,c,b,e){var k=this;e=e||{};var v=f.toString(),g=l.g(),v=v.replace("SCRIPT_PLACEHOLDER",g),v=URL.createObjectURL(new Blob(["(",v,")()"],{type:"application/javascript"}));this.f=[];this.d=[];this.m=[];this.n=[];this.j=new Worker(v);this.j.onmessage=function(a){h(k,a)};this.o=null;this.h=0;this.r=e.functionsBufferSize||5;this.k=[];this.j.postMessage({p:"ctor",Q:a,I:c,b:b,a:++p,v:!1,N:d.u()})}function f(){importScripts("SCRIPT_PLACEHOLDER");l.C()}function h(a,c){var b=c.data.a;
switch(c.data.type){case "functionCalled":--a.h;n(a);break;case "promiseResult":var e=a.d[b];delete a.d[b];e.resolve(c.data.result);break;case "promiseFailure":e=a.d[b];delete a.d[b];e.reject(c.data.reason);break;case "userData":null!==a.o&&a.o(c.data.W);break;case "callback":b=a.f[c.data.a];if(void 0===b)throw"Unexpected message from SlaveWorker of callback ID: "+c.data.a+". Maybe should indicate isMultipleTimesCallback = true on creation?";b.q||a.t(a.f[c.data.a]);null!==b.s&&b.s.apply(null,c.data.b);
break;case "subWorkerCtor":var b=new Worker(c.data.P),d=c.data.c;a.m[d]=b;a.n.push(b);b.onmessage=function(b){w(a,b.ports,!1,{p:"subWorkerOnMessage",c:d,data:b.data})};break;case "subWorkerPostMessage":b=a.m[c.data.c];b.postMessage(c.data.data);break;case "subWorkerTerminate":b=a.m[c.data.c];b.terminate();break;default:throw"Unknown message from AsyncProxySlave of type: "+c.data.type;}}function w(a,c,b,e){a.h>=a.r?a.k.push({V:c,L:b,message:e}):k(a,c,b,e)}function k(a,c,b,e){b&&++a.h;a.j.postMessage(e,
c)}function n(a){for(;a.h<a.r&&0<a.k.length;){var c=a.k.shift();k(a,c.V,c.L,c.message)}}var p=0,x=!1,q=function(){var a=location.href,c=a.lastIndexOf("/");0<=c&&(a=a.substring(0,c));return a}();d.prototype.U=function(a){this.o=a};d.prototype.terminate=function(){this.j.terminate();for(var a=0;a<this.n.length;++a)this.n[a].terminate()};d.prototype.G=function(a,c,b){b=b||{};var e=!!b.isReturnPromise,d=b.transferables,f=b.pathsToTransferablesInPromiseResult,g=++p,h=null,q=this;e&&(h=new Promise(function(a,
b){q.d[g]={resolve:a,reject:b}}));(b.isSendImmediately?k:w)(this,d,!0,{p:a,b:c||[],a:g,v:e,O:f});if(e)return h};d.prototype.X=function(a,c,b){b=b||{};var e=++p;c={M:!0,q:!!b.isMultipleTimeCallback,a:e,H:c,w:b.pathsToTransferables};this.f[e]={q:!!b.isMultipleTimeCallback,a:e,s:a,w:b.pathsToTransferables};return c};d.prototype.t=function(a){delete this.f[a.a]};d.u=function(){x=!0;return q};d.D=function(a){if(q!==a&&x)throw"Previous values returned from getMasterEntryUrl is wrong. Avoid calling it within the slave c`tor";
q=a};return d}();var t=function(){function d(d){if(null===h)throw"AsyncProxy internal error: SubWorkerEmulationForChrome not initialized";this.i=++f;h[this.i]=this;self.postMessage({type:"subWorkerCtor",c:this.i,P:d})}var f=0,h=null;d.K=function(d){h=d};d.prototype.postMessage=function(d,f){self.postMessage({type:"subWorkerPostMessage",c:this.i,data:d},f)};d.prototype.terminate=function(d,f){self.postMessage({type:"subWorkerTerminate",c:this.i},f)};return d}(),l=function(){function d(){var a=self[q],c=[null].concat(w(arguments));
return new (Function.prototype.bind.apply(a,c))}function f(a,c){if(void 0!==a){for(var b=Array(a.length),e=0;e<a.length;++e){for(var d=a[e],f=c,g=0;g<d.length;++g)f=f[d[g]];b[e]=f}return b}}function h(a){var c=a.data.p,b=a.data.b,e=a.data.a,f=a.data.v,h=a.data.O;switch(c){case "ctor":m.D(a.data.N);e=a.data.Q;q=a.data.I;for(var g=0;g<e.length;++g)importScripts(e[g]);p=d.apply(null,b);return;case "subWorkerOnMessage":x[a.data.c].onmessage({data:a.data.data});return}b=Array(a.data.b.length);for(g=0;g<
a.data.b.length;++g){var r=a.data.b[g];void 0!==r&&null!==r&&r.M&&(r=k.A(r));b[g]=r}for(var g=p,n;g&&!(n=p[c]);)g=g.__proto__;if(!n)throw"AsyncProxy error: could not find function "+n;b=n.apply(p,b);f&&k.B(e,b,h);self.postMessage({type:"functionCalled",a:a.data.a,result:null})}function w(a){for(var c=Array(a.length),b=0;b<a.length;++b)c[b]=a[b];return c}var k={},n=null,p,x={},q;k.C=function(){self.onmessage=h};k.T=function(a){d=a};k.S=function(a){n=a};k.R=function(a){self.postMessage({type:"userData",
W:a})};k.B=function(a,c,b){c.then(function(c){var d=f(b,c);self.postMessage({type:"promiseResult",a:a,result:c},d)})["catch"](function(b){self.postMessage({type:"promiseFailure",a:a,reason:b})})};k.A=function(a){var c=!1;return function(){if(c)throw"Callback is called twice but isMultipleTimeCallback = false";var b=w(arguments);null!==n&&n.call(p,"callback",a.H,b);var d=f(a.w,b);self.postMessage({type:"callback",a:a.a,b:b},d);a.q||(c=!0)}};k.g=function(){return u.g(Error())};void 0===self.Worker&&
(t.K(x),self.Worker=t);return k}();var u=function(){function d(){this.l={};this.e=null}d.prototype.F=function(f){f=d.g(f);this.l[f]||(this.l[f]=!0,this.e=null)};d.prototype.J=function(){if(null===this.e){this.e=[];for(var d in this.l)this.e.push(d)}return this.e};d.g=function(d){var h=(new RegExp(arguments.callee.name+" \\((.+?):\\d+:\\d+\\)")).exec(d.stack.trim());if(h&&""!==h[1]||(h=(new RegExp(/.+\/(.*?):\d+(:\d+)*$/)).exec(d.stack.trim()))&&""!==h[1])return h[1];if(void 0!=d.fileName)return d.fileName;throw"ImageDecoderFramework.js: Could not get current script URL";
};return d}();self.AsyncProxy={};self.AsyncProxy.AsyncProxySlave=l;self.AsyncProxy.AsyncProxyMaster=m;self.AsyncProxy.ScriptsToImportPool=u;t.prototype.postMessage=t.prototype.postMessage;t.prototype.terminate=t.prototype.terminate;l.setSlaveSideCreator=l.T;l.setBeforeOperationListener=l.S;l.sendUserDataToMaster=l.R;l.wrapPromiseFromSlaveSide=l.B;l.wrapCallbackFromSlaveSide=l.A;m.prototype.setUserDataHandler=m.prototype.U;m.prototype.terminate=m.prototype.terminate;m.prototype.callFunction=m.prototype.G;
m.prototype.wrapCallback=m.prototype.X;m.prototype.freeCallback=m.prototype.t;m.getEntryUrl=m.u;u.prototype.addScriptFromErrorWithStackTrace=u.prototype.F;u.prototype.getScriptsForWorkerImport=u.prototype.J;
